version: '3.8'

services:
  web:
    build: ./test_task
    container_name: 'test-task'
    command: sh -c "uvicorn main:app"
    network_mode: host
    volumes:
      - ./test_task:/test_task

  redis:
    image: redis
    ports:
      - 6379:6379

  postgresql:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage
    ports:
      - 8010:5432